### ISSUE TITLE
Issue while installing oliver with Python 3.6.8

### ISSUE THREAD

**Issue by xzhub** [stjudecloud/oliver#20]
**Describe the bug**

**To Reproduce**

1. Install

```
$ pip install stjudecloud-oliver
```

2.  Run

```
$ oliver configure
Traceback (most recent call last):
  File "/usr/local/bin/oliver", line 7, in <module>
    from oliver.__main__ import main
  File "/usr/local/lib/python3.6/site-packages/oliver/__main__.py", line 10, in <module>
    from oliver.subcommands import (
  File "/usr/local/lib/python3.6/site-packages/oliver/subcommands/abort.py", line 5, in <module>
    from ..lib import api, reporting
  File "/usr/local/lib/python3.6/site-packages/oliver/lib/reporting.py", line 3, in <module>
    from typing import List, Dict, OrderedDict as OrderedDictType
ImportError: cannot import name 'OrderedDict'

```

**Desktop (please complete the following information):**
 - OS: Centos 7.4
 - Python: 3.6.8

**Comment by xzhub** [comment]
More info:

```
$ pip install --upgrade pip
Requirement already up-to-date: pip in ./py3env/lib/python3.6/site-packages (20.0.2)

$ pip install stjudecloud-oliver
Requirement already satisfied: stjudecloud-oliver in ./py3env/lib/python3.6/site-packages (1.2.1)
Requirement already satisfied: tzlocal<3.0.0,>=2.0.0 in ./py3env/lib/python3.6/site-packages (from stjudecloud-oliver) (2.0.0)
Requirement already satisfied: requests<3.0.0,>=2.22.0 in ./py3env/lib/python3.6/site-packages (from stjudecloud-oliver) (2.23.0)
Requirement already satisfied: pendulum<3.0.0,>=2.0.5 in ./py3env/lib/python3.6/site-packages (from stjudecloud-oliver) (2.1.0)
Requirement already satisfied: python-semantic-release<5.0.0,>=4.8.0 in ./py3env/lib/python3.6/site-packages (from stjudecloud-oliver) (4.12.1)
Requirement already satisfied: tabulate<0.9.0,>=0.8.6 in ./py3env/lib/python3.6/site-packages (from stjudecloud-oliver) (0.8.7)
Requirement already satisfied: aiohttp<4.0.0,>=3.6.2 in ./py3env/lib/python3.6/site-packages (from stjudecloud-oliver) (3.6.2)
Requirement already satisfied: boto3<2.0.0,>=1.11.9 in ./py3env/lib/python3.6/site-packages (from stjudecloud-oliver) (1.12.39)
Requirement already satisfied: azure-cosmos<4.0.0,>=3.1.2 in ./py3env/lib/python3.6/site-packages (from stjudecloud-oliver) (3.1.2)
Requirement already satisfied: logzero<2.0.0,>=1.5.0 in ./py3env/lib/python3.6/site-packages (from stjudecloud-oliver) (1.5.0)
Requirement already satisfied: pytz in ./py3env/lib/python3.6/site-packages (from tzlocal<3.0.0,>=2.0.0->stjudecloud-oliver) (2019.3)
Requirement already satisfied: chardet<4,>=3.0.2 in ./py3env/lib/python3.6/site-packages (from requests<3.0.0,>=2.22.0->stjudecloud-oliver) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in ./py3env/lib/python3.6/site-packages (from requests<3.0.0,>=2.22.0->stjudecloud-oliver) (2.9)
Requirement already satisfied: certifi>=2017.4.17 in ./py3env/lib/python3.6/site-packages (from requests<3.0.0,>=2.22.0->stjudecloud-oliver) (2020.4.5.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./py3env/lib/python3.6/site-packages (from requests<3.0.0,>=2.22.0->stjudecloud-oliver) (1.25.8)
Requirement already satisfied: pytzdata>=2018.3 in ./py3env/lib/python3.6/site-packages (from pendulum<3.0.0,>=2.0.5->stjudecloud-oliver) (2019.3)
Requirement already satisfied: python-dateutil<3.0,>=2.6 in ./py3env/lib/python3.6/site-packages (from pendulum<3.0.0,>=2.0.5->stjudecloud-oliver) (2.8.1)
Requirement already satisfied: click<8.0,>=2.0 in ./py3env/lib/python3.6/site-packages (from python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (7.1.1)
Requirement already satisfied: wheel in ./py3env/lib/python3.6/site-packages (from python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (0.34.2)
Requirement already satisfied: python-gitlab==1.10.0 in ./py3env/lib/python3.6/site-packages (from python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (1.10.0)
Requirement already satisfied: gitpython~=2.1 in ./py3env/lib/python3.6/site-packages (from python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (2.1.15)
Requirement already satisfied: semver~=2.2 in ./py3env/lib/python3.6/site-packages (from python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (2.9.1)
Requirement already satisfied: invoke==0.11.1 in ./py3env/lib/python3.6/site-packages (from python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (0.11.1)
Requirement already satisfied: twine~=1.12 in ./py3env/lib/python3.6/site-packages (from python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (1.15.0)
Requirement already satisfied: toml==0.10.0 in ./py3env/lib/python3.6/site-packages (from python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (0.10.0)
Requirement already satisfied: ndebug~=0.1 in ./py3env/lib/python3.6/site-packages (from python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (0.1.1)
Requirement already satisfied: multidict<5.0,>=4.5 in ./py3env/lib/python3.6/site-packages (from aiohttp<4.0.0,>=3.6.2->stjudecloud-oliver) (4.7.5)
Requirement already satisfied: idna-ssl>=1.0; python_version < "3.7" in ./py3env/lib/python3.6/site-packages (from aiohttp<4.0.0,>=3.6.2->stjudecloud-oliver) (1.1.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in ./py3env/lib/python3.6/site-packages (from aiohttp<4.0.0,>=3.6.2->stjudecloud-oliver) (3.0.1)
Requirement already satisfied: typing-extensions>=3.6.5; python_version < "3.7" in ./py3env/lib/python3.6/site-packages (from aiohttp<4.0.0,>=3.6.2->stjudecloud-oliver) (3.7.4.2)
Requirement already satisfied: attrs>=17.3.0 in ./py3env/lib/python3.6/site-packages/attrs-19.3.0-py3.6.egg (from aiohttp<4.0.0,>=3.6.2->stjudecloud-oliver) (19.3.0)
Requirement already satisfied: yarl<2.0,>=1.0 in ./py3env/lib/python3.6/site-packages (from aiohttp<4.0.0,>=3.6.2->stjudecloud-oliver) (1.4.2)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in ./py3env/lib/python3.6/site-packages (from boto3<2.0.0,>=1.11.9->stjudecloud-oliver) (0.9.5)
Requirement already satisfied: botocore<1.16.0,>=1.15.39 in ./py3env/lib/python3.6/site-packages (from boto3<2.0.0,>=1.11.9->stjudecloud-oliver) (1.15.39)
Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in ./py3env/lib/python3.6/site-packages (from boto3<2.0.0,>=1.11.9->stjudecloud-oliver) (0.3.3)
Requirement already satisfied: six>=1.6 in ./py3env/lib/python3.6/site-packages/six-1.14.0-py3.6.egg (from azure-cosmos<4.0.0,>=3.1.2->stjudecloud-oliver) (1.14.0)
Requirement already satisfied: gitdb2<3,>=2 in ./py3env/lib/python3.6/site-packages (from gitpython~=2.1->python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (2.0.6)
Requirement already satisfied: pkginfo>=1.4.2 in ./py3env/lib/python3.6/site-packages (from twine~=1.12->python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (1.5.0.1)
Requirement already satisfied: requests-toolbelt!=0.9.0,>=0.8.0 in ./py3env/lib/python3.6/site-packages (from twine~=1.12->python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (0.9.1)
Requirement already satisfied: readme-renderer>=21.0 in ./py3env/lib/python3.6/site-packages (from twine~=1.12->python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (25.0)
Requirement already satisfied: setuptools>=0.7.0 in ./py3env/lib/python3.6/site-packages (from twine~=1.12->python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (46.1.3)
Requirement already satisfied: tqdm>=4.14 in ./py3env/lib/python3.6/site-packages (from twine~=1.12->python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (4.45.0)
Requirement already satisfied: colorama>=0.4.1 in ./py3env/lib/python3.6/site-packages (from ndebug~=0.1->python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (0.4.3)
Requirement already satisfied: docutils<0.16,>=0.10 in ./py3env/lib/python3.6/site-packages (from botocore<1.16.0,>=1.15.39->boto3<2.0.0,>=1.11.9->stjudecloud-oliver) (0.15.2)
Requirement already satisfied: smmap2>=2.0.0 in ./py3env/lib/python3.6/site-packages (from gitdb2<3,>=2->gitpython~=2.1->python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (3.0.1)
Requirement already satisfied: bleach>=2.1.0 in ./py3env/lib/python3.6/site-packages (from readme-renderer>=21.0->twine~=1.12->python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (3.1.4)
Requirement already satisfied: Pygments>=2.5.1 in ./py3env/lib/python3.6/site-packages (from readme-renderer>=21.0->twine~=1.12->python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (2.6.1)
Requirement already satisfied: smmap>=3.0.1 in ./py3env/lib/python3.6/site-packages (from smmap2>=2.0.0->gitdb2<3,>=2->gitpython~=2.1->python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (3.0.2)
Requirement already satisfied: webencodings in ./py3env/lib/python3.6/site-packages (from bleach>=2.1.0->readme-renderer>=21.0->twine~=1.12->python-semantic-release<5.0.0,>=4.8.0->stjudecloud-oliver) (0.5.1)
```

**Comment by a-frantz** [comment]
`oliver` requires Python 3.8. Thank you for pointing out that this isn't in the docs yet. I'll leave the issue open for now in case you run into any other issues, but `pip install`ing with a Python3.8 environment should solve this.

**Comment by xzhub** [comment]
I just installed oliver with miniconda, the python version is 3.7.6. Should I switch to python 3.8, or this would be fine?

olver runs, seems no issue so far.

**Comment by a-frantz** [comment]
That should be fine. I checked my environment and I was running 3.8. If you're not having issues, keep going with what you have. I will update the docs to specify Python >=3.7
