### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'str' when use 'inspect'

### ISSUE THREAD

**Issue by kevin-furant** [stjudecloud/oliver#60]
> oliver i e52a9bdd-2d0c-452b-82d0-0073e0861805
Traceback (most recent call last):
  File "/share/nastj10/B2C_RD_P2/USER/fuxiangke/software/Miniconda3/envs/cromwell/bin/oliver", line 10, in <module>
    sys.exit(main())
  File "/share/nastj10/B2C_RD_P2/USER/fuxiangke/software/Miniconda3/envs/cromwell/lib/python3.7/site-packages/oliver/__main__.py", line 125, in main
    asyncio.run(run())
  File "/share/nastj10/B2C_RD_P2/USER/fuxiangke/software/Miniconda3/envs/cromwell/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/share/nastj10/B2C_RD_P2/USER/fuxiangke/software/Miniconda3/envs/cromwell/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/share/nastj10/B2C_RD_P2/USER/fuxiangke/software/Miniconda3/envs/cromwell/lib/python3.7/site-packages/oliver/__main__.py", line 120, in run
    await args["func"](args, cromwell)
  File "/share/nastj10/B2C_RD_P2/USER/fuxiangke/software/Miniconda3/envs/cromwell/lib/python3.7/site-packages/oliver/subcommands/inspect.py", line 112, in call
    calls = sorted(calls, key=lambda k: k["Start"])
TypeError: '<' not supported between instances of 'NoneType' and 'str'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3101e84350>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f3101e13130>, 53136171.49227757)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f3101e84610>

can you give me some help? thank you very much!

**Comment by a-frantz** [comment]
Is this a persistent error, or have you only witnessed it this one time?

I believe the cause is a task being in an unexpected transient state (which it shouldn't be in for long). Attempting to `inspect` again should work. If not, I'll need some more information about your Cromwell server.

**Comment by kevin-furant** [comment]
> Is this a persistent error, or have you only witnessed it this one time?
> 
> I believe the cause is a task being in an unexpected transient state (which it shouldn't be in for long). Attempting to `inspect` again should work. If not, I'll need some more information about your Cromwell server.

This is indeed sometimes in the task, I tried today, can work normally again, thank you very much!
